/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_spo_jni_JNI */

#ifndef _Included_com_example_spo_jni_JNI
#define _Included_com_example_spo_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_spo_jni_JNI
 * Method:    OR
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_spo_jni_JNI_OR
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_spo_jni_JNI
 * Method:    MULTIPLY
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_spo_jni_JNI_MULTIPLY
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
